# Generated by Django 2.0.6 on 2018-06-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body2',
            field=models.TextField(default='in text please!!'),
            preserve_default=False,
        ),
    ]
