# Generated by Django 2.1 on 2018-08-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_body2'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMstr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=30)),
                ('update_time', models.DateTimeField()),
                ('regist_time', models.DateTimeField()),
                ('loginflg', models.CharField(max_length=1)),
                ('delflg', models.CharField(max_length=1)),
            ],
        ),
    ]
