# Generated by Django 2.1 on 2018-08-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_usermstr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermstr',
            name='mail',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='usermstr',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
