# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-18 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180818_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kakikomi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.CharField(max_length=255)),
            ],
        ),
    ]
